name: 'Create And Publish Release'

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:

  generate_changelog:
    name: Create and Commit Changelog > Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update main CHANGELOG.md
        id: changelog
        uses: Requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}

      - name: Commit Changelogs and update.json
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: master
          commit_message: 'docs: update changelogs for ${{ github.ref_name }}'
